on:
  push:
      branches:
        - master
      
jobs:
  compile:
    name: compile pdf files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Setup texlive-full
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: Run python script
        run: python build.py
      - name: Commit change
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "compiled PDF file"
          git push
