on:
  push:
      branches:
        - master
      
jobs:
  compile:
    name: compile pdf files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          path: master
      - name: Run python script
        run: python3 ./build.py
      - name: Commit change
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "compiled PDF file"
          git push
